language: csharp
sudo: required
dist: trusty # Ubuntu 14.04
dotnet : 2.1.402
env:
 - FAKE_DETAILED_ERRORS=true HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force openssl ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt update; sudo apt install ruby ruby-dev rubygems-integration build-essential -y ; fi 
  - gem install --no-ri --no-rdoc fpm

mono:
  - 5.0.1

script: 
  - dotnet build build.proj /nologo /verbosity:minimal /p:Parallel=true

branches:
  except:
    - gh-pages
