image: Visual Studio 2017
install:
  - cinst fake
build_script:
# See https://stackoverflow.com/a/12866669/1269722
# Problem is that colors are lost
# Don't blame me but powershell is the bigest crap on earth
  - cmd: fake.exe run build.fsx --parallel 3

#  - ps: .\build.cmd
on_failure:
  - appveyor PushArtifact FAKE.svclog
test: off
environment:
  PAKET_BOOTSTRAPPER_TRACE: true

artifacts:
  - path: 'nuget\dotnetcore\*.nupkg'
    type: NuGetPackage
  - path: 'nuget\legacy\*.nupkg'
    type: NuGetPackage
  - path: 'nuget\dotnetcore\Fake.netcore\*.zip'
    type: Zip
